import {NextResponse} from 'next/server';
import {getSessionUser} from '@/lib/auth';
import {currentCreator,sameOrigin} from '@/lib/authorize';
import {addDivision,disableAnnouncement,getAnnouncements,getDivisions,saveAnnouncement,saveWebhook,webhookStatus,type AnnouncementPlacement,type WebhookKind} from '@/lib/creator-config';

export const dynamic='force-dynamic';export const runtime='nodejs';
type Session={id:string;username:string;exp:number};
async function creator(request:Request){const session=await getSessionUser<Session>(request);return session&&await currentCreator(request)?session:null}
export async function GET(request:Request){const session=await creator(request);if(!session)return NextResponse.json({error:'Área exclusiva de Criadores.'},{status:403});try{return NextResponse.json({integrations:await webhookStatus(),divisions:await getDivisions(),announcements:await getAnnouncements(true)},{headers:{'cache-control':'no-store'}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Falha ao carregar configurações.'},{status:503})}}
export async function POST(request:Request){const session=await creator(request);if(!session)return NextResponse.json({error:'Área exclusiva de Criadores.'},{status:403});if(!sameOrigin(request))return NextResponse.json({error:'Origem inválida.'},{status:403});try{const body=await request.json()as Record<string,unknown>;if(body.action==='webhook'){await saveWebhook(String(body.kind) as WebhookKind,String(body.url||''),session.username);return NextResponse.json({ok:true,integrations:await webhookStatus()})}if(body.action==='division'){const groupId=Number(body.groupId);if(!Number.isSafeInteger(groupId)||groupId<=0)throw new Error('Informe um ID de comunidade válido.');const response=await fetch(`https://groups.roblox.com/v1/groups/${groupId}`,{cache:'no-store'});if(!response.ok)throw new Error('A comunidade não foi encontrada no Roblox.');const group=await response.json()as{name?:string};const name=group.name?.trim();if(!name)throw new Error('O Roblox não retornou o nome da comunidade.');const sigla=String(body.sigla||name.split(/\s+/).map(word=>word[0]).join('')).toUpperCase();return NextResponse.json({ok:true,divisions:await addDivision({groupId,name,sigla,actor:session.username})},{status:201})}if(body.action==='announcement'){const announcement=await saveAnnouncement({title:String(body.title||''),message:String(body.message||''),color:String(body.color||'#426B9D'),placement:(body.placement==='topbar'?'topbar':'below') as AnnouncementPlacement,startsAt:body.startsAt?String(body.startsAt):undefined,endsAt:body.endsAt?String(body.endsAt):null,actor:session.username});return NextResponse.json({ok:true,announcement},{status:201})}if(body.action==='disable-announcement'){await disableAnnouncement(String(body.id||''));return NextResponse.json({ok:true})}return NextResponse.json({error:'Ação desconhecida.'},{status:400})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Não foi possível salvar.'},{status:400})}}
