'use client';
/* eslint-disable @next/next/no-img-element -- Roblox avatar URLs are dynamic. */

import{useEffect,useMemo,useState}from'react';
import{PATENTES}from'@/lib/patentes';

export type ClientCdp={id:string;userId:string;username:string;roleId:string;rankName:string;durationDays:number;status:'active'|'completed'|'cancelled'|'consumed';startedAt:string;endsAt:string;completedAt:string|null;cancelledAt:string|null;consumedAt:string|null;createdByUsername:string;reason:string};
type Member={userId:string;username:string;rankName:string;roleId:string;cdpActive:boolean;cdpStartedAt:string|null;cdpEndsAt:string|null;cdpRecordId?:string|null};

function remaining(end:string,now:number){
  const milliseconds=Math.max(0,new Date(end).getTime()-now);
  const days=Math.floor(milliseconds/86_400_000);const hours=Math.floor(milliseconds%86_400_000/3_600_000);const minutes=Math.floor(milliseconds%3_600_000/60_000);
  return milliseconds<=0?'Tempo concluído':days?`${days}d ${hours}h ${minutes}min restantes`:`${hours}h ${minutes}min restantes`;
}

function useClock(){const[now,setNow]=useState(0);useEffect(()=>{const first=setTimeout(()=>setNow(Date.now()),0);const timer=setInterval(()=>setNow(Date.now()),30_000);return()=>{clearTimeout(first);clearInterval(timer)}},[]);return now}

function previewPersonalRecord(user:{id:string;username:string}):ClientCdp{return{id:'preview-cdp',userId:user.id,username:user.username,roleId:'807380036',rankName:'[SLD] Soldado',durationDays:2,status:'active',startedAt:'2026-08-28T12:00:00.000-03:00',endsAt:'2026-08-30T12:00:00.000-03:00',completedAt:null,cancelledAt:null,consumedAt:null,createdByUsername:'ComandanteEB',reason:'CDP demonstrativa'}}

export function CdpPersonalStatus({user,preview=false}:{user:{id:string;username:string;avatar?:string;rank?:string};preview?:boolean}){
  const[record,setRecord]=useState<ClientCdp|null>(()=>preview?previewPersonalRecord(user):null);const[loading,setLoading]=useState(!preview);const[configured,setConfigured]=useState(preview);const[error,setError]=useState('');const now=useClock();
  useEffect(()=>{
    if(preview)return;
    fetch(`/api/cdp?userId=${encodeURIComponent(user.id)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível consultar sua CDP.');setConfigured(Boolean(data.configured));setRecord(data.record||null)}).catch(caught=>setError(caught instanceof Error?caught.message:'Não foi possível consultar sua CDP.')).finally(()=>setLoading(false));
  },[preview,user.id,user.username]);
  const active=record?.status==='active';const completed=record?.status==='completed';
  return<div className="cdp-personal-grid"><article className="panel cdp-profile-card"><div className="cdp-profile-top"><span className="cdp-personal-avatar">{user.avatar?<img src={user.avatar} alt=""/>:user.username.slice(0,2).toUpperCase()}</span><div><span className="kicker">SITUAÇÃO INDIVIDUAL</span><h2>{user.username}</h2><p>{user.rank||'Membro do Exército'}</p></div></div>{loading?<div className="cdp-state neutral"><span>···</span><div><b>Consultando sua CDP</b><small>Aguarde a sincronização.</small></div></div>:error?<div className="cdp-state danger"><span>!</span><div><b>CDP indisponível</b><small>{error}</small></div></div>:!configured?<div className="cdp-state pending"><span>DB</span><div><b>Banco ainda não conectado</b><small>Adicione DATABASE_URL na Vercel para ativar a CDP real.</small></div></div>:active?<div className="cdp-state active"><span>◷</span><div><b>CDP em andamento</b><strong>{now?remaining(record.endsAt,now):'Calculando tempo...'}</strong><small>Iniciada por {record.createdByUsername}</small></div></div>:completed?<div className="cdp-state ready"><span>✓</span><div><b>CDP concluída</b><strong>Elegível para promoção</strong><small>Esta conclusão será consumida no próximo UP.</small></div></div>:<div className="cdp-state neutral"><span>—</span><div><b>Fora da CDP</b><small>Nenhum ciclo de capacitação está em andamento.</small></div></div>}{record&&<div className="cdp-facts"><div><small>PATENTE DO CICLO</small><b>{record.rankName}</b></div><div><small>DURAÇÃO</small><b>{record.durationDays} dia(s)</b></div><div><small>INÍCIO</small><b>{new Date(record.startedAt).toLocaleDateString('pt-BR')}</b></div><div><small>PREVISÃO</small><b>{new Date(record.endsAt).toLocaleString('pt-BR')}</b></div></div>}</article><aside className="panel cdp-rules"><span className="kicker">COMO FUNCIONA</span><h2>Progressão protegida</h2><ol><li><span>1</span><div><b>Início autorizado</b><small>Um administrador inicia a CDP pela ficha do militar.</small></div></li><li><span>2</span><div><b>Tempo por patente</b><small>A duração configurada começa a contar automaticamente.</small></div></li><li><span>3</span><div><b>Conclusão automática</b><small>Ao terminar o prazo, o militar fica elegível.</small></div></li><li><span>4</span><div><b>Uso único</b><small>O UP consome a CDP; a próxima patente exige novo ciclo.</small></div></li></ol></aside></div>
}

export function CdpMemberControl({member,canManage,preview=false,onChange}:{member:Member;canManage:boolean;preview?:boolean;onChange?:(record:ClientCdp|null)=>void}){
  const initial=member.cdpActive&&member.cdpRecordId&&member.cdpStartedAt&&member.cdpEndsAt?{id:member.cdpRecordId,userId:member.userId,username:member.username,roleId:member.roleId,rankName:member.rankName,durationDays:0,status:'active' as const,startedAt:member.cdpStartedAt,endsAt:member.cdpEndsAt,completedAt:null,cancelledAt:null,consumedAt:null,createdByUsername:'Comando',reason:''}:null;
  const[record,setRecord]=useState<ClientCdp|null>(initial);const[reason,setReason]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[confirm,setConfirm]=useState<'complete'|'cancel'|null>(null);const now=useClock();
  useEffect(()=>{if(!preview)fetch(`/api/cdp?userId=${member.userId}`).then(r=>r.json()).then(data=>{if(data.record)setRecord(data.record)}).catch(()=>null)},[member.userId,preview]);
  const active=record?.status==='active';
  async function act(action:'start'|'complete'|'cancel'){
    setLoading(true);setError('');
    try{
      let next:ClientCdp;
      if(preview){const start=new Date();const end=new Date(start.getTime()+2*86_400_000);next=action==='start'?{id:'preview-member-cdp',userId:member.userId,username:member.username,roleId:member.roleId,rankName:member.rankName,durationDays:2,status:'active',startedAt:start.toISOString(),endsAt:end.toISOString(),completedAt:null,cancelledAt:null,consumedAt:null,createdByUsername:'ComandanteEB',reason:reason||'Início pelo painel'}:{...(record as ClientCdp),status:action==='complete'?'completed':'cancelled',completedAt:action==='complete'?new Date().toISOString():null,cancelledAt:action==='cancel'?new Date().toISOString():null};await new Promise(resolve=>setTimeout(resolve,350))}
      else{const response=await fetch('/api/cdp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,userId:member.userId,username:member.username,recordId:record?.id,reason})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível atualizar a CDP.');next=data.record}
      setRecord(next);setReason('');setConfirm(null);onChange?.(next);
    }catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível atualizar a CDP.')}finally{setLoading(false)}
  }
  return<div className="cdp-member-control"><div className={`member-cdp-status ${active?'active':record?.status==='completed'?'ready':'inactive'}`}><span>CDP</span><b>{active?'Em andamento':record?.status==='completed'?'Concluída · apto para UP':'Não está em CDP'}</b><small>{active&&now?remaining(record.endsAt,now):record?.status==='completed'?'A conclusão será usada na próxima promoção.':'Nenhum ciclo de capacitação iniciado'}</small></div>{canManage&&<div className="cdp-actions">{!active?<><label className="field-label" htmlFor={`cdp-reason-${member.userId}`}>Observação inicial</label><textarea id={`cdp-reason-${member.userId}`} rows={3} maxLength={500} placeholder="Ex.: Início da capacitação para progressão..." value={reason} onChange={event=>setReason(event.target.value)}/><button type="button" className="primary" disabled={loading} onClick={()=>act('start')}>{loading?'Iniciando...':'Iniciar CDP'}</button></>:confirm?<div className={`cdp-confirm ${confirm==='cancel'?'danger':''}`}><b>{confirm==='complete'?'Concluir esta CDP agora?':'Cancelar esta CDP?'}</b>{confirm==='cancel'&&<textarea rows={3} maxLength={500} placeholder="Motivo obrigatório do cancelamento" value={reason} onChange={event=>setReason(event.target.value)}/>}<div><button type="button" className="secondary" onClick={()=>setConfirm(null)}>Voltar</button><button type="button" className={confirm==='cancel'?'danger-btn':'primary'} disabled={loading||(confirm==='cancel'&&reason.trim().length<5)} onClick={()=>act(confirm)}>{loading?'Processando...':'Confirmar'}</button></div></div>:<div className="cdp-action-row"><button type="button" className="secondary" onClick={()=>setConfirm('complete')}>Concluir agora</button><button type="button" className="danger-btn" onClick={()=>setConfirm('cancel')}>Cancelar CDP</button></div>}{error&&<div className="cdp-inline-error" role="alert">{error}</div>}</div>}</div>
}

export function CdpSettingsManager({preview=false}:{preview?:boolean}){
  const defaults=useMemo(()=>PATENTES.filter(rank=>rank.promovivel).map(rank=>({roleId:rank.roleId,sigla:rank.sigla,nome:rank.nome,days:rank.cdpDias,promovivel:true})),[]);
  const[settings,setSettings]=useState(defaults);const[loading,setLoading]=useState(!preview);const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[configured,setConfigured]=useState(preview);const[error,setError]=useState('');
  useEffect(()=>{if(preview)return;fetch('/api/cdp/settings').then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data.settings||defaults);setConfigured(Boolean(data.configured))}).catch(caught=>setError(caught instanceof Error?caught.message:'Falha ao consultar configurações.')).finally(()=>setLoading(false))},[preview,defaults]);
  function change(roleId:string,days:number){setSettings(current=>current.map(item=>item.roleId===roleId?{...item,days:Math.max(0,Math.min(30,days))}:item));setSaved(false)}
  async function save(){setSaving(true);setError('');try{if(preview){await new Promise(resolve=>setTimeout(resolve,350));setSaved(true);return}const response=await fetch('/api/cdp/settings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({settings:settings.map(item=>({roleId:item.roleId,days:item.days}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível salvar.');setSettings(data.settings);setConfigured(true);setSaved(true)}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível salvar.')}finally{setSaving(false)}}
  return<div className="cdp-settings"><div className="settings-heading"><div><h3>Tempo de CDP por patente — EXÉRCITO</h3><p>O prazo é contado a partir do início autorizado. Zero significa que a patente não exige CDP.</p></div><span className={`config-status ${configured?'active':'pending'}`}>{configured?'BANCO CONECTADO':'BANCO PENDENTE'}</span></div>{loading?<div className="history-empty"><span>DB</span><div><b>Carregando configurações</b><p>Consultando os prazos salvos.</p></div></div>:<div className="cdp-config-list">{settings.map(item=><div className="cdp-config-row" key={item.roleId}><span className="cdp-sigla">[{item.sigla}]</span><span className="cdp-nome">{item.nome}</span><label className="cdp-input"><input aria-label={`Dias de CDP para ${item.nome}`} type="number" min={0} max={30} value={item.days} onChange={event=>change(item.roleId,Number(event.target.value))}/><small>dias</small></label></div>)}</div>}{error&&<div className="cdp-inline-error">{error}</div>}{saved?<div className="action-success"><span>✓</span><b>Configurações salvas</b></div>:<button type="button" className="primary" style={{marginTop:12}} disabled={saving||loading} onClick={save}>{saving?'Salvando...':'Salvar alterações'}</button>}</div>
}
