'use client';
import {useEffect,useState} from 'react';
type Announcement={id:string;title:string;message:string;color:string;placement:'topbar'|'below';endsAt:string|null;active:boolean};
type Division={groupId:number;sigla:string;nome:string};
export function CreatorOperations({preview=false}:{preview?:boolean}){
 const[integrations,setIntegrations]=useState({trainings:false,logs:false,database:preview}),[divisions,setDivisions]=useState<Division[]>([]),[announcements,setAnnouncements]=useState<Announcement[]>([]),[status,setStatus]=useState(''),[saving,setSaving]=useState(false);
 const[trainingUrl,setTrainingUrl]=useState(''),[logsUrl,setLogsUrl]=useState(''),[groupId,setGroupId]=useState(''),[sigla,setSigla]=useState('');
 const[title,setTitle]=useState(''),[message,setMessage]=useState(''),[color,setColor]=useState('#426B9D'),[placement,setPlacement]=useState<'topbar'|'below'>('below'),[endsAt,setEndsAt]=useState('');
 async function load(){if(preview){setIntegrations({trainings:true,logs:true,database:true});setDivisions([{groupId:521106467,sigla:'EXÉRCITO',nome:'Exército Brasileiro do Mig'}]);return}const r=await fetch('/api/creator/config',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setIntegrations(d.integrations);setDivisions(d.divisions);setAnnouncements(d.announcements)}
 useEffect(()=>{const timer=setTimeout(()=>{load().catch(error=>setStatus(error.message))},0);return()=>clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function action(body:Record<string,unknown>){if(preview){setStatus('Configuração simulada com sucesso.');return null}setSaving(true);setStatus('');try{const r=await fetch('/api/creator/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setStatus('Configuração salva e já aplicada.');return d}catch(error){setStatus(error instanceof Error?error.message:'Não foi possível salvar.');return null}finally{setSaving(false)}}
 async function saveHook(kind:'trainings'|'logs',url:string){const done=await action({action:'webhook',kind,url});if(done){if(kind==='trainings')setTrainingUrl('');else setLogsUrl('')}}
 async function addGroup(){const done=await action({action:'division',groupId:Number(groupId),sigla});if(done){setGroupId('');setSigla('')}}
 async function createAnnouncement(){const done=await action({action:'announcement',title,message,color,placement,endsAt:endsAt?new Date(endsAt).toISOString():null});if(done){setTitle('');setMessage('');setEndsAt('')}}
 return <div className="creator-operations"><section className="config-block"><h2>Integrações do Discord</h2><p className="field-hint">Cole o webhook completo. Ele será criptografado no servidor e nunca será exibido novamente.</p>{([['trainings','Treinamentos',trainingUrl,setTrainingUrl,integrations.trainings],['logs','Logs gerais',logsUrl,setLogsUrl,integrations.logs]] as const).map(([kind,label,value,setValue,active])=><div className="config-line" key={kind}><div><b>{label}</b><small>{active?'Configurado':'Pendente'}</small></div><input type="password" autoComplete="off" placeholder="https://discord.com/api/webhooks/..." value={value} onChange={event=>setValue(event.target.value)}/><button className="m-button primary" disabled={saving||!value} onClick={()=>void saveHook(kind,value)}>Salvar</button></div>)}</section>
 <section className="config-block"><h2>Comunidades das divisões</h2><p className="field-hint">Adicione pelo ID numérico. O nome será conferido diretamente no Roblox.</p><div className="config-line"><input inputMode="numeric" placeholder="ID da comunidade" value={groupId} onChange={event=>setGroupId(event.target.value.replace(/\D/g,''))}/><input maxLength={12} placeholder="Sigla" value={sigla} onChange={event=>setSigla(event.target.value.toUpperCase())}/><button className="m-button primary" disabled={saving||!groupId} onClick={()=>void addGroup()}>Adicionar divisão</button></div><div className="chip-list">{divisions.map(item=><span className="m-tag" key={item.groupId}>{item.sigla} · {item.groupId}</span>)}</div></section>
 <section className="config-block"><h2>Central de anúncios</h2><p className="field-hint">Publique um aviso com cor, posição e término opcionais.</p><div className="announcement-form"><input placeholder="Título do anúncio" maxLength={80} value={title} onChange={event=>setTitle(event.target.value)}/><textarea rows={3} placeholder="Mensagem para os militares" maxLength={500} value={message} onChange={event=>setMessage(event.target.value)}/><div className="config-line"><label>Cor <input type="color" value={color} onChange={event=>setColor(event.target.value)}/></label><select value={placement} onChange={event=>setPlacement(event.target.value as 'topbar'|'below')}><option value="topbar">Na barra superior</option><option value="below">Abaixo da barra</option></select><label>Encerrar em <input type="datetime-local" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label><button className="m-button primary" disabled={saving||title.trim().length<3||message.trim().length<5} onClick={()=>void createAnnouncement()}>Publicar anúncio</button></div></div>{announcements.map(item=><div className="announcement-row" key={item.id} style={{borderLeftColor:item.color}}><div><b>{item.title}</b><small>{item.message}</small></div><span className="m-tag">{item.active?'Ativo':'Encerrado'}</span>{item.active&&<button className="m-button" onClick={()=>void action({action:'disable-announcement',id:item.id})}>Encerrar</button>}</div>)}</section>
 {!integrations.database&&<div className="m-alert">Conecte DATABASE_URL na Vercel para salvar ranking, logs, CDP e configurações.</div>}{status&&<div className="m-alert" role="status">{status}</div>}</div>
}
