'use client';
import {useEffect,useState} from 'react';
import {getHierarchySnapshot} from '@/lib/hierarchy-snapshot';
import {DIVISOES} from '@/lib/divisoes-mig';
import {Avatar,Icon,json} from './Manager';
type Role={id:string;name:string;rank:number};
type Found={userId:string;username:string;rankName:string;avatar?:string};
export function DirectRankChanger({preview=false}:{preview?:boolean}){
 const[groupId,setGroupId]=useState(521106467),[roles,setRoles]=useState<Role[]>(()=>preview?getHierarchySnapshot()[0].roles.filter(r=>r.rank>0&&r.rank<253):[]),[query,setQuery]=useState(preview?'gabribor_sola':''),[found,setFound]=useState<Found|null>(null),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[review,setReview]=useState(false),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(preview)return;fetch('/api/hierarquia').then(r=>r.json()).then(d=>setRoles((d.groups?.find((g:{groupId:number})=>g.groupId===groupId)?.roles||[]).filter((r:Role)=>r.rank>0&&r.rank<253))).catch(()=>setError('Não foi possível carregar os cargos atuais.'))},[preview,groupId]);
 async function lookup(){if(!query.trim())return;setBusy(true);setError('');try{if(preview){setFound({userId:'391027',username:query.trim(),rankName:'[REC] Recruta'});setReview(true);return}const d=await json(`/api/militares/search?channel=Militares&q=${encodeURIComponent(query.trim())}&division=EXÉRCITO`);const member=(d.members||[]).find((m:Found)=>m.userId===query.trim()||m.username.toLowerCase()===query.trim().toLowerCase());if(!member)throw new Error('Informe o username ou ID exato do militar.');setFound(member);setReview(true)}catch(e){setError(e instanceof Error?e.message:'Não foi possível localizar o militar.')}finally{setBusy(false)}}
 async function apply(){if(!found||!target||reason.trim().length<5)return;setBusy(true);setError('');try{if(!preview){const r=await fetch('/api/ranks/change',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:'direct',channel:'Gestão do criador',userId:found.userId,groupId,targetRoleId:target,reason:reason.trim(),confirm:true})});const d=await r.json();if(!r.ok)throw new Error(d.error)}setDone(true)}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar o cargo.')}finally{setBusy(false)}}
 if(done)return <section className="m-panel m-empty"><Icon name="award" size={34}/><h3>Cargo alterado com sucesso</h3><p>{preview?'Simulação concluída; nenhum cargo real foi alterado.':'O Roblox confirmou o novo cargo de '+found?.username+'.'}</p><button className="m-button" onClick={()=>{setDone(false);setReview(false);setFound(null);setTarget('');setReason('')}}>Alterar outro militar</button></section>;
 return <section className="m-panel direct-rank"><div className="creator-callout"><Icon name="shield"/><span>Alteração direta de cargo · exclusiva para Criadores</span></div><div className="stepper"><span className={!review?'current':''}>1. Militar</span><span className={review?'current':''}>2. Novo cargo</span></div><div className="filter-row"><label className="m-search"><Icon name="search"/><input aria-label="Buscar militar para alterar cargo" placeholder="Username ou ID do Roblox" value={query} disabled={review||busy} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()}/></label><select aria-label="Comunidade do cargo" value={groupId} disabled={review||busy} onChange={e=>setGroupId(Number(e.target.value))}>{DIVISOES.map(d=><option key={d.groupId} value={d.groupId}>{d.sigla}</option>)}</select><button className="m-button primary" disabled={busy||!query.trim()||review} onClick={()=>void lookup()}>{busy?'Consultando…':'Localizar'}</button></div>{found&&<div className="direct-member"><Avatar name={found.username} src={found.avatar}/><div><b>{found.username}</b><small>Cargo atual: {found.rankName}</small></div></div>}{review&&<div className="direct-form"><label htmlFor="direct-target">Alterar cargo para</label><select id="direct-target" aria-label="Novo cargo" value={target} disabled={busy} onChange={e=>setTarget(e.target.value)}><option value="">Escolha um cargo da hierarquia</option>{roles.sort((a,b)=>b.rank-a.rank).map(r=><option key={r.id} value={r.id}>[{r.rank}] {r.name}</option>)}</select><label htmlFor="direct-reason">Motivo da alteração</label><textarea id="direct-reason" rows={3} maxLength={500} placeholder="Ex.: ajuste de patente autorizado pelo Criador" value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/><div className="batch-actions"><button className="m-button" onClick={()=>{setReview(false);setFound(null)}}>Trocar militar</button><button className="m-button primary" disabled={busy||!target||reason.trim().length<5} onClick={()=>void apply()}>{busy?'Enviando…':preview?'Simular alteração':'Confirmar alteração no Roblox'}</button></div></div>}{error&&<div className="m-alert" role="alert">{error}</div>}</section>
}
