'use client';
import {useEffect,useState} from 'react';
import {getHierarchySnapshot} from '@/lib/hierarchy-snapshot';
import {CdpSettingsManager} from './CdpSystem';
import {BulkRankManager} from './BulkRankManager';
import {DiscordConfiguration} from './DiscordConfiguration';
import {CreatorOperations} from './CreatorOperations';
import {LiveHierarchy} from './LiveHierarchy';
import {DirectRankChanger} from './DirectRankChanger';
import {DIVISOES} from '@/lib/divisoes-mig';
import {CHANNELS,type Permissions} from '@/lib/access';
import {filterActivities,trainingRanking,remainingCdp,EVENT_LABELS,type Activity,type RosterMember,type ManagerData} from '@/lib/manager';
import {Avatar,Blank,Icon,demoMembers,type SessionUser} from './Manager';
export function Hierarchy({preview=false}:{preview?:boolean}){return <LiveHierarchy preview={preview}/>} 
export function Members({preview}:{preview:boolean}){const [query,setQuery]=useState(''),[division,setDivision]=useState(''),[members,setMembers]=useState<RosterMember[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<RosterMember|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0);
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError('');setSelected(null);try{if(preview){const list=demoMembers.filter(m=>(!division||division==='EXÉRCITO'||m.division===division)&&`${m.username} ${m.userId} ${m.rankName}`.toLowerCase().includes(query.toLowerCase()));setMembers(list);setTotal(list.length)}else{const r=await fetch(`/api/militares/search?channel=Militares&q=${encodeURIComponent(query)}&division=${encodeURIComponent(division)}`,{signal:c.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setMembers(d.members);setTotal(d.total)}}catch(e){if(!c.signal.aborted){setError(e instanceof Error?e.message:'Falha na busca.');setMembers([])}}finally{if(!c.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);c.abort()}},[query,division,preview]);
 return <><section className="m-panel"><div className="filter-row"><label className="m-search"><Icon name="search"/><input aria-label="Buscar militar" placeholder="Nome, ID ou patente do militar" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><select aria-label="Filtrar divisão" value={division} onChange={e=>{setDivision(e.target.value);setPage(1)}}><option value="">Todas as divisões</option>{DIVISOES.map(d=><option key={d.sigla}>{d.sigla}</option>)}</select></div>{loading?<Blank title="Consultando efetivo…" text="Buscando os militares do grupo."/>:error?<div role="alert" className="m-alert">{error}</div>:members.length?<><p className="result-count">{total} militares encontrados{total>members.length?' · refine a busca para encontrar outros resultados':''}</p><div className="member-grid">{members.slice((page-1)*12,page*12).map(m=><button className="member-card" key={m.userId} onClick={()=>setSelected(m)}><Avatar name={m.username} src={m.avatar}/><b>{m.username}</b><small>{m.rankName}</small><span className="m-tag">{m.division}</span></button>)}</div><Pagination page={page} count={members.length} size={12} change={setPage}/></>:<Blank text="Tente outro nome, ID, patente ou divisão."/>}</section>{selected&&<section className="m-panel member-selected"><div className="panel-title"><h2>{selected.username}</h2><button className="icon-button" aria-label="Fechar detalhes" onClick={()=>setSelected(null)}><Icon name="close"/></button></div><p>{selected.rankName} · {selected.division}</p><p>ID Roblox: {selected.userId}</p>{!preview&&<a className="text-button" href={`https://www.roblox.com/users/${selected.userId}/profile`} target="_blank" rel="noreferrer">Abrir perfil no Roblox ↗</a>}</section>}</>}
function Pagination({page,count,size,change}:{page:number;count:number;size:number;change:(p:number)=>void}){const pages=Math.max(1,Math.ceil(count/size));return <div className="pagination"><button className="m-button" disabled={page<=1} onClick={()=>change(page-1)}>Anterior</button><span>Página {page} de {pages}</span><button className="m-button" disabled={page>=pages} onClick={()=>change(page+1)}>Próxima</button></div>}
export function Cdp({data,user}:{data:ManagerData|null;user:SessionUser}){const [query,setQuery]=useState(''),[now,setNow]=useState(0);useEffect(()=>{const tick=()=>setNow(Date.now());const initial=setTimeout(tick,0);const t=setInterval(tick,1000);return()=>{clearTimeout(initial);clearInterval(t)}},[]);const mine=data?.cdpMembers?.find(m=>m.userId===user.id);const members=data?.cdpMembers?.filter(m=>m.cdpFim&&new Date(m.cdpFim).getTime()>now&&`${m.username} ${m.rankName}`.toLowerCase().includes(query.toLowerCase()))||[];return <><section className="m-panel cdp-personal"><Icon name="clock" size={34}/><div><h2>Minha capacitação</h2><p>{mine?.cdpFim?remainingCdp(mine.cdpFim,now):'Nenhum período de CDP registrado para sua conta.'}</p><small>A ausência de registro não confirma elegibilidade para promoção.</small></div></section><section className="m-panel"><div className="panel-title"><h2>Militares em CDP</h2><span className="m-tag">{members.length} registros</span></div><label className="m-search"><Icon name="search"/><input aria-label="Buscar CDP" placeholder="Filtrar por militar ou patente" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="member-grid">{members.map(m=><article className="member-card" key={m.userId}><Avatar name={m.username}/><b>{m.username}</b><small>{m.rankName}</small><span className="m-tag">{remainingCdp(m.cdpFim!,now)}</span></article>)}</div>{!members.length&&<Blank text="Não há períodos de capacitação disponíveis para esta consulta."/>}</section></>}
export function Logs({logs,history=false,available}:{logs:Activity[];history?:boolean;available?:boolean}){const [query,setQuery]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(1);const filtered=filterActivities(history?logs.filter(l=>['promocao','rebaixamento'].includes(l.tipo)):logs,query,type);return <section className="m-panel"><div className="filter-row"><label className="m-search"><Icon name="search"/><input aria-label="Buscar registro" placeholder="Nome, ID, responsável ou descrição" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><select aria-label="Tipo de ação" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">Todas as ações</option>{Object.entries(EVENT_LABELS).filter(([k])=>!history||['promocao','rebaixamento'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{filtered.length?<><div className="table-scroll"><table><thead><tr><th>Militar</th><th>Ação</th><th>Descrição</th><th>Responsável</th><th>Data</th></tr></thead><tbody>{filtered.slice((page-1)*10,page*10).map(l=><tr key={l.id}><td><b>{l.username}</b><small>{l.userId}</small></td><td><span className="m-tag">{EVENT_LABELS[l.tipo]||l.tipo}</span></td><td>{l.descricao}</td><td>{l.autorUsername||'—'}</td><td>{new Date(l.timestamp).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div><Pagination page={page} count={filtered.length} size={10} change={setPage}/></>:<Blank text={available===false?'O histórico precisa de armazenamento persistente na hospedagem.':'Nenhuma ação encontrada. Tente outros filtros ou aguarde novos registros.'}/>}</section>}
export function Ranking({logs}:{logs:Activity[]}){const month=new Date().toISOString().slice(0,7);const ranked=trainingRanking(logs.filter(l=>l.timestamp.slice(0,7)===month));return <section className="m-panel"><div className="panel-title"><h2>Instrutores do mês</h2><Icon name="award"/></div>{ranked.length?ranked.map((r,i)=><div className="ranking-row" key={r.id}><strong>{i+1}</strong><Avatar name={r.name} src={r.avatar}/><b>{r.name}</b><span>{r.count} treinos</span></div>):<Blank title="O ranking começa com o primeiro treino" text="Treinamentos com um instrutor identificado entram na classificação."/>}</section>}
export function Creator({preview,permissions,update,canSave,roles}:{preview:boolean;permissions:Permissions;update:(p:Permissions)=>void;canSave:boolean;roles:Array<{id:string;name:string;rank:number}>}){const [tab,setTab]=useState('Permissões das guias'),[draft,setDraft]=useState<Permissions>({...permissions}),[status,setStatus]=useState(''),[saving,setSaving]=useState(false);const gameRoles=(roles.length?roles:getHierarchySnapshot()[0].roles).filter((r,i,list)=>r.rank>0&&r.rank<255&&list.findIndex(x=>x.rank===r.rank)===i).sort((a,b)=>a.rank-b.rank);const dirty=JSON.stringify(draft)!==JSON.stringify(permissions);
 async function save(){setSaving(true);setStatus('');try{if(preview){update(draft);setStatus('Permissões aplicadas apenas nesta demonstração.');return}const r=await fetch('/api/permissions',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw new Error(d.error);update(draft);setStatus('Permissões salvas. As novas consultas já seguem estas regras.')}catch(e){setStatus(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
 return <section className="m-panel"><div className="creator-callout"><Icon name="shield"/><span>Somente [CR] Criador pode gerenciar o sistema.</span></div><div className="tabs">{['Permissões das guias','Hierarquia e CDP','Gestão em massa','Alterar cargo','Códigos de UP','Divisões e anúncios','Integrações'].map(t=><button key={t} onClick={()=>{setTab(t);setStatus('')}} className={tab===t?'active':''}>{t}</button>)}</div>{tab==='Permissões das guias'?<><h2>Quem pode ver cada guia?</h2><p className="field-hint">A patente escolhida e todas as superiores terão acesso. Criadores sempre têm acesso, inclusive à gestão. Ver uma guia não concede autorização para modificar o sistema.</p>{!preview&&!canSave&&<div className="m-alert">Conecte o armazenamento persistente da Vercel para salvar estas regras. Até lá, valem as permissões atuais.</div>}<div className="permissions-list">{CHANNELS.map(channel=><div className="permission-row" key={channel}><label htmlFor={`permission-${channel}`}>{channel}</label><select id={`permission-${channel}`} aria-label={`Patente mínima para ${channel}`} value={draft[channel]} onChange={e=>{setDraft({...draft,[channel]:e.target.value});setStatus('')}}><option value="all">Todos os militares</option><option value="creator">Somente Criadores</option>{gameRoles.map(p=><option key={p.rank} value={`rank:${p.rank}`}>A partir de {p.name} (nível {p.rank})</option>)}</select></div>)}</div><div className="save-bar"><span>{dirty?'Alterações não salvas':'Nenhuma alteração pendente'}</span><button className="m-button" disabled={!dirty||saving} onClick={()=>setDraft({...permissions})}>Descartar alterações</button><button className="m-button primary" disabled={!dirty||saving||(!preview&&!canSave)} onClick={()=>void save()}>{saving?'Salvando…':preview?'Aplicar na demonstração':'Salvar permissões'}</button></div></>:tab==='Hierarquia e CDP'?<CdpSettingsManager preview={preview}/>:tab==='Gestão em massa'?<BulkRankManager previewMode={preview}/>:tab==='Alterar cargo'?<DirectRankChanger preview={preview}/>:tab==='Códigos de UP'?<Blank title="Códigos de UP ainda não habilitados" text="A criação e o resgate exigem controle persistente de uso e integração de patentes com o Roblox. Esta gestão é exclusiva de Criadores."/>:tab==='Divisões e anúncios'?<CreatorOperations preview={preview}/>:<DiscordConfiguration preview={preview}/>}{status&&<div className="m-alert" role="status">{status}</div>}</section>
}
export function Help(){return <section className="m-panel prose"><h2>Como podemos ajudar?</h2>{[['Como consultar minha patente?','Abra Meu perfil para ver a patente identificada no seu último login. Em Hierarquia você encontra a estrutura do MIG, se a guia estiver liberada para você.'],['Como funciona a entrega de patente?','Selecione o grupo, informe usernames ou IDs e consulte os militares. A busca exige correspondência exata. O envio ao Roblox depende da integração de escrita.'],['Quem pode modificar o sistema?','Somente [CR] Criador. Administradores, Developers e Sub Criadores não recebem acesso à gestão automaticamente.'],['Como são definidas as permissões?','O Criador escolhe a patente mínima para cada guia. A patente selecionada e todas as superiores têm acesso. Essa liberação não autoriza modificar configurações.'],['A minha CDP acabou?','Consulte o prazo registrado em CDP. Se não houver registro, confirme com o responsável antes de solicitar promoção.'],['Minha patente ou divisão mudou. O que faço?','Saia e entre novamente com Roblox para renovar as informações da sessão.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>}



