'use client';
import {useEffect,useState} from 'react';
import {ClipboardCheck,Plus,ShieldCheck,RefreshCw,ArrowRight} from 'lucide-react';
import {DIVISOES} from '@/lib/divisoes-mig';
import {REQUEST_STATUS,allowedTransition,type PromotionRequest} from '@/lib/promotion-model';
import {RobloxIdentity} from './RobloxIdentity';
import {FeedbackToast} from './FeedbackToast';
export default function PromotionRequests({preview=false,creator=false}:{preview?:boolean;creator?:boolean}){
  const [items,setItems]=useState<PromotionRequest[]>([]),[groups,setGroups]=useState(DIVISOES),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[canSave,setCanSave]=useState(preview),[canReview,setCanReview]=useState(preview&&creator);
  const [target,setTarget]=useState(''),[group,setGroup]=useState(521106467),[reason,setReason]=useState(''),[status,setStatus]=useState('all'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false),[retry,setRetry]=useState(0);
  const [selected,setSelected]=useState<PromotionRequest|null>(null),[action,setAction]=useState('approve'),[note,setNote]=useState(''),[confirm,setConfirm]=useState(false);
  useEffect(()=>{const c=new AbortController();const timer=setTimeout(async()=>{
    setLoading(true);
    try{
      if(preview){setItems(JSON.parse(sessionStorage.getItem('mig-request-preview')||'[]'));return}
      const [r,d]=await Promise.all([fetch('/api/promotions/requests',{signal:c.signal,cache:'no-store'}),fetch('/api/divisions',{signal:c.signal})]);
      const data=await r.json();if(!r.ok)throw new Error(data.error);setItems(data.requests);setCanReview(data.canReview);setCanSave(data.canSave);
      if(d.ok)setGroups((await d.json()).divisions);
    }catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Falha na consulta.')}finally{if(!c.signal.aborted)setLoading(false)}
  },0);return()=>{clearTimeout(timer);c.abort()}},[preview,retry]);
  function update(item:PromotionRequest){setItems(previous=>{const next=[item,...previous.filter(r=>r.id!==item.id)];if(preview)sessionStorage.setItem('mig-request-preview',JSON.stringify(next));return next})}
  async function create(event:React.FormEvent){
    event.preventDefault();setSaving(true);setError('');
    try{
      if(preview){if(items.some(i=>i.userId===target&&i.groupId===group&&['pending','approved','executing','reconciliation'].includes(i.status)))throw new Error('Já existe uma solicitação aberta.');const now=new Date().toISOString();update({id:crypto.randomUUID(),userId:target,username:target,groupId:group,community:groups.find(g=>g.groupId===group)?.sigla||'EXÉRCITO',currentId:'demo-a',currentName:'[REC] Recruta',targetId:'demo-b',targetName:'[SLD] Soldado',reason,status:'pending',requestedBy:'demo',requestedName:'ComandanteMIG',reviewedName:null,reviewNote:'',createdAt:now,updatedAt:now})}
      else{const r=await fetch('/api/promotions/requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:target,groupId:group,reason})});const data=await r.json();if(!r.ok)throw new Error(data.error);update(data.request)}
      setCreating(false);setTarget('');setReason('');setNotice(preview?'Solicitação simulada.':'Solicitação enviada para análise.');
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar.')}finally{setSaving(false)}
  }
  async function review(event:React.FormEvent){
    event.preventDefault();if(!selected)return;setSaving(true);setError('');
    try{
      if(preview){if(!allowedTransition(selected.status,action))throw new Error('Ação não permitida.');update({...selected,status:action==='approve'?'approved':action==='reject'?'rejected':'applied',reviewNote:note,reviewedName:'ComandanteMIG',updatedAt:new Date().toISOString()})}
      else{const r=await fetch('/api/promotions/requests',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,action,note,confirm})});const data=await r.json();if(!r.ok){setRetry(n=>n+1);throw new Error(data.error)}update(data.request)}
      setSelected(null);setError('');setNotice(preview?'Revisão simulada; nenhum cargo real foi alterado.':action==='execute'?'Promoção confirmada pelo Roblox.':'Parecer registrado nos logs.');
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível revisar.')}finally{setSaving(false)}
  }
  const filtered=items.filter(i=>status==='all'||i.status===status);
  return <div className="requests-workspace"><section className="request-intro"><ClipboardCheck size={28}/><div><h2>Da indicação à confirmação</h2><p>Registre o motivo, aguarde a análise e acompanhe a promoção. Aprovar uma solicitação não altera o cargo; a execução exige uma segunda confirmação.</p></div></section>
    <div className="catalog-toolbar"><label>Exibir<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas as solicitações</option>{Object.entries(REQUEST_STATUS).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><div className="action-row"><button className="m-button" disabled={loading||saving} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/>Atualizar</button><button className="m-button primary" disabled={loading||saving||!canSave} onClick={()=>setCreating(true)}><Plus size={17}/>Solicitar promoção</button></div></div>
    {error&&<div className="m-alert" role="alert">{error}</div>}{!loading&&!canSave&&<div className="m-alert">Conecte o banco de dados para habilitar as solicitações e a auditoria.</div>}
    {creating&&<section className="m-panel"><h2>Nova solicitação</h2><form className="catalog-editor" onSubmit={create}><div className="editor-fields"><label>Username Roblox do militar<input required autoComplete="off" placeholder="Ex.: gabribor_sola" pattern="[a-zA-Z0-9_]{3,20}" minLength={3} maxLength={20} value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Comunidade<select value={group} onChange={e=>setGroup(Number(e.target.value))}>{groups.map(g=><option value={g.groupId} key={g.groupId}>{g.sigla}</option>)}</select></label></div><label>Justificativa<textarea required minLength={10} maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Informe o treinamento e os requisitos cumpridos."/></label><div className="save-bar"><button type="button" className="m-button" disabled={saving} onClick={()=>setCreating(false)}>Cancelar</button><button className="m-button primary" disabled={saving||!canSave}>{saving?'Enviando…':'Enviar para análise'}</button></div></form></section>}
    {selected&&<section className="m-panel request-review"><h2>{action==='execute'?'Confirmar promoção no Roblox':'Parecer do Criador'}</h2><p>{selected.username} · {selected.currentName} → {selected.targetName}</p><form className="catalog-editor" onSubmit={review}><label>Parecer<textarea required minLength={5} maxLength={500} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label>{action==='execute'&&<label className="confirm-check"><input type="checkbox" required checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Confirmo a alteração {preview?'simulada':'real'} desta patente.</label>}<div className="save-bar"><button className="m-button" type="button" disabled={saving} onClick={()=>setSelected(null)}>Cancelar</button><button className="m-button primary" disabled={saving}>{saving?'Registrando…':action==='execute'?'Confirmar execução':action==='approve'?'Aprovar solicitação':'Recusar solicitação'}</button></div></form></section>}
    {loading?<div className="panel-skeleton" role="status" aria-label="Carregando solicitações"><span/><span/><span/></div>:filtered.length?<div className="request-list">{filtered.map(item=><article className="m-panel request-card" key={item.id}><div className="request-card-head"><RobloxIdentity userId={preview?undefined:item.userId} username={item.username} avatar={item.avatar} detail={item.community}/><span className={`m-tag request-status status-${item.status}`}>{preview&&item.status==='applied'?'Execução simulada':REQUEST_STATUS[item.status]}</span></div><div className="request-ranks"><span>{item.currentName}</span><ArrowRight size={18}/><strong>{item.targetName}</strong></div><p>{item.reason}</p><details><summary>Histórico da solicitação</summary><div className="request-person"><small>Solicitante · {new Date(item.createdAt).toLocaleString('pt-BR')}</small><RobloxIdentity userId={preview?undefined:item.requestedBy} username={item.requestedName} avatar={item.requestedAvatar}/></div>{item.reviewedName&&<div className="request-person"><small>Responsável pelo parecer</small><RobloxIdentity userId={preview?undefined:item.reviewedBy} username={item.reviewedName} avatar={item.reviewedAvatar}/><p>{item.reviewNote}</p></div>}<small>Referência: {item.id}</small></details>{canReview&&['pending','approved'].includes(item.status)&&<div className="action-row">{(item.status==='pending'?['approve','reject']:['execute','reject']).map(a=><button className={`m-button ${a==='reject'?'':'primary'}`} disabled={saving} key={a} onClick={()=>{setSelected(item);setAction(a);setNote('');setConfirm(false)}}>{a==='approve'?'Analisar aprovação':a==='reject'?'Recusar':'Executar promoção'}</button>)}</div>}{item.status==='reconciliation'&&<p className="inline-warning">Confira o cargo no Roblox e a CDP. A repetição automática está bloqueada.</p>}</article>)}</div>:<div className="m-empty"><ShieldCheck size={34}/><h3>Nenhuma solicitação neste filtro</h3><p>As indicações enviadas aparecerão aqui com seu estado de análise.</p></div>}
    <FeedbackToast message={notice} onClose={()=>setNotice('')}/>
  </div>;
}
