'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Check,Copy,ExternalLink,LoaderCircle,ShieldCheck,X} from 'lucide-react';
import {useRouter} from 'next/navigation';
type Challenge={challengeId:string;code:string;username:string;expiresAt:string;profileUrl:string};
const errors:Record<string,string>={config:'A integração com o Roblox precisa ser configurada.',cancelled:'O acesso foi cancelado.',invalid:'A tentativa expirou. Comece novamente.',token:'O Roblox não aceitou o código de autorização.',profile:'Não foi possível ler seu perfil.',nogroup:'Sua conta não pertence ao Exército.',service:'O Roblox está indisponível no momento.',required:'Entre para abrir sua Central.',rate:'Muitas tentativas. Aguarde alguns minutos.'};
export default function PublicAccess(){
 const router=useRouter();
 const[consent,setConsent]=useState(false),[bio,setBio]=useState(false),[username,setUsername]=useState(''),[challenge,setChallenge]=useState<Challenge|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[copied,setCopied]=useState(false),[loginError,setLoginError]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>{setConsent(document.cookie.includes('eb_consent=v1'));const code=new URLSearchParams(location.search).get('login');if(code)setLoginError(errors[code]||'Não foi possível entrar. Tente novamente.')},0);return()=>clearTimeout(timer)},[]);
 function accept(){document.cookie='eb_consent=v1; Max-Age=31536000; Path=/; SameSite=Lax';setConsent(true)}
 function oauth(){if(!consent){setMessage('Confirme os Termos e a Política de Privacidade antes de continuar.');return}router.push('/api/auth/roblox/start')}
 async function startBio(event:React.FormEvent){event.preventDefault();if(!consent){setMessage('Confirme os Termos e a Política de Privacidade.');return}setBusy(true);setMessage('');try{const response=await fetch('/api/auth/bio/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username})});const data=await response.json();if(!response.ok)throw new Error(data.error);setChallenge(data)}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível gerar o código.')}finally{setBusy(false)}}
 async function verify(){if(!challenge)return;setBusy(true);setMessage('');try{const response=await fetch('/api/auth/bio/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId:challenge.challengeId,code:challenge.code})});const data=await response.json();if(!response.ok)throw new Error(data.error);router.push('/central')}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível confirmar a bio.')}finally{setBusy(false)}}
 return <><aside className="access-card"><div className="access-head"><span className="access-seal"><ShieldCheck/></span><div><small>ACESSO RESTRITO</small><b>Identificação militar</b></div></div><div className="access-title"><span>IDENTIFICAÇÃO OPERACIONAL</span><h2>Acesse seu posto de instrução</h2><p>Sua conta Roblox confirma patente, função e permissões de serviço.</p></div>{loginError&&<div className="access-error" role="alert">{loginError}</div>}<button className="roblox-login" onClick={oauth}><i><span/></i>Continuar com Roblox<ArrowRight/></button><button className="bio-login" onClick={()=>{setBio(true);setMessage('')}}>Verificar pela bio</button><label className="consent-row"><input type="checkbox" checked={consent} onChange={event=>{if(event.target.checked)accept();else setConsent(false)}}/><i className="consent-box" aria-hidden="true">{consent&&<Check/>}</i><span>Li e aceito os <Link href="/termos">Termos</Link> e a <Link href="/privacidade">Política de Privacidade</Link>.</span></label>{message&&!bio&&<p className="access-message">{message}</p>}<div className="access-proof"><span><ShieldCheck/></span><div><b>Permissão operacional</b><small>Seu cargo determina quais treinamentos e ações você pode registrar.</small></div></div><footer><span><Check/> Autenticação segura</span><small>Nenhuma senha é armazenada.</small></footer></aside>
 {bio&&<div className="bio-overlay" role="dialog" aria-modal="true" aria-labelledby="bio-title"><div className="bio-modal"><button className="modal-close" onClick={()=>setBio(false)} aria-label="Fechar"><X/></button><span className="landing-eyebrow">VERIFICAÇÃO ALTERNATIVA</span><h2 id="bio-title">Confirme pela bio do Roblox</h2>{!challenge?<><p>Informe seu nome de usuário. Você receberá um código temporário para colocar na descrição do perfil.</p><form onSubmit={startBio}><label>Nome de usuário Roblox<input value={username} onChange={event=>setUsername(event.target.value)} minLength={3} maxLength={20} placeholder="Ex.: gabribor_sola" required autoFocus/></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:'Gerar código de verificação'}</button></form></>:<><p>Adicione exatamente este código à descrição de <b>@{challenge.username}</b>. Ele expira em 10 minutos e funciona uma única vez.</p><div className="bio-code"><code>{challenge.code}</code><button onClick={async()=>{await navigator.clipboard.writeText(challenge.code);setCopied(true)}} aria-label="Copiar código">{copied?<Check/>:<Copy/>}</button></div><a className="profile-link" href={challenge.profileUrl} target="_blank" rel="noreferrer">Abrir perfil no Roblox <ExternalLink/></a><button className="bio-verify" onClick={verify} disabled={busy}>{busy?<LoaderCircle className="spin"/>:'Já coloquei o código — verificar'}</button><button className="bio-reset" onClick={()=>setChallenge(null)}>Usar outra conta</button></>}{message&&<p className="access-message" role="alert">{message}</p>}</div></div>}
 </>}
