import Link from 'next/link';
import {ArrowRight,BarChart3,CheckCircle2,ClipboardCheck,LockKeyhole,Medal,ShieldCheck,Users,UserRoundCheck} from 'lucide-react';
import PublicAccess from './PublicAccess';
const features=[{icon:Users,title:'Efetivo sincronizado',text:'Militares, patentes e divisões identificados pelas comunidades oficiais.'},{icon:Medal,title:'Promoções responsáveis',text:'CDP, treinamentos e motivos reunidos em um fluxo claro.'},{icon:ClipboardCheck,title:'Auditoria permanente',text:'Cada ação registra responsável, militar, mudança e horário.'},{icon:BarChart3,title:'Comando em tempo real',text:'Ranking, alertas e atividade recente para decisões rápidas.'}];
export default function PublicLanding(){return <main className="public-site">
 <header className="public-nav"><Link className="public-brand" href="/" aria-label="EB DO MIG, início"><span>EB</span><div><b>EB DO MIG</b><small>CENTRAL MILITAR</small></div></Link><nav aria-label="Navegação principal"><a href="#recursos">Recursos</a><a href="#seguranca">Segurança</a><a href="#como-funciona">Como funciona</a><Link href="/termos">Termos</Link></nav><a className="nav-access" href="#acesso">Acessar Central <ArrowRight size={15}/></a></header>
 <section className="landing-hero" id="acesso"><div className="hero-copy"><span className="landing-eyebrow"><i/> SISTEMA OFICIAL DE COMANDO</span><h1>Disciplina nos registros.<br/><em>Clareza no comando.</em></h1><p className="hero-lead">A estrutura operacional do EB DO MIG em um único lugar: efetivo, treinamentos, promoções e auditoria conectados à sua identidade Roblox.</p><ul className="hero-points"><li><CheckCircle2/> Hierarquia validada pela comunidade</li><li><CheckCircle2/> Ações protegidas por patente</li><li><CheckCircle2/> Histórico rastreável do início ao fim</li></ul><div className="trust-row"><span><ShieldCheck/> Sessão protegida</span><span><LockKeyhole/> Nenhuma senha armazenada</span><span>Grupo 521106467</span></div></div><PublicAccess/></section>
 <section className="feature-section" id="recursos"><div className="section-heading"><span>OPERAÇÃO INTEGRADA</span><h2>Uma Central construída para o serviço militar.</h2><p>Menos planilhas dispersas. Mais contexto, controle e responsabilidade em cada decisão.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text},index)=><article key={title}><div><span>0{index+1}</span><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="security-section" id="seguranca"><div className="security-visual" aria-hidden="true"><div className="radar-sweep"/><i className="radar-axis horizontal"/><i className="radar-axis vertical"/><i className="radar-blip blip-one"/><i className="radar-blip blip-two"/><i className="radar-blip blip-three"/><div className="security-ring"><ShieldCheck/><span>ACESSO<br/>VERIFICADO</span></div></div><div className="security-copy"><span>SEGURANÇA OPERACIONAL</span><h2>Cada militar vê e executa somente o que sua patente permite.</h2><p>A Central consulta sua identidade Roblox e aplica as regras da hierarquia na interface e no servidor. Alterações sensíveis deixam um registro permanente.</p><div className="security-list"><div><UserRoundCheck/><span><b>Identidade confirmada</b><small>OAuth oficial ou código temporário na bio.</small></span></div><div><LockKeyhole/><span><b>Permissão em duas camadas</b><small>Proteção visual e validação no servidor.</small></span></div><div><ClipboardCheck/><span><b>Auditoria imutável</b><small>Responsável, alvo, antes, depois e horário.</small></span></div></div></div></section>
 <section className="steps-section" id="como-funciona"><div className="section-heading"><span>ENTRADA EM SERVIÇO</span><h2>Da identificação ao painel em três passos.</h2></div><div className="steps-grid"><article><b>01</b><h3>Identifique-se</h3><p>Entre pelo Roblox ou use a verificação pela bio para confirmar a conta.</p></article><article><b>02</b><h3>Validamos sua patente</h3><p>O sistema consulta o Exército e suas divisões, sem pedir sua senha.</p></article><article><b>03</b><h3>Assuma seu posto</h3><p>A Central abre os guias, ações e dados liberados para sua posição.</p></article></div></section>
 <section className="numbers-band"><div><strong>1</strong><span>Central unificada</span></div><div><strong>24h</strong><span>Sessão protegida</span></div><div><strong>100%</strong><span>Ações auditáveis</span></div><div><strong>2</strong><span>Formas de acesso</span></div></section>
 <section className="faq-section"><div className="section-heading"><span>DÚVIDAS FREQUENTES</span><h2>Antes de entrar em serviço.</h2></div><div className="faq-list"><details><summary>O site armazena minha senha do Roblox?</summary><p>Não. O acesso principal acontece no Roblox, e a Central recebe apenas a confirmação necessária.</p></details><details><summary>Não consigo usar o login do Roblox. O que faço?</summary><p>Use “Verificar pela bio”. O código é temporário, de uso único e deve ser colocado na descrição do perfil.</p></details><details><summary>Por que algumas áreas não aparecem?</summary><p>Guias e operações seguem sua patente. Configurações e compras permanecem exclusivas dos Criadores.</p></details></div></section>
 <section className="final-cta"><span>PRONTO PARA ASSUMIR O COMANDO?</span><h2>Sua patente abre a porta.<br/>A disciplina mantém a confiança.</h2><a href="#acesso">Entrar na Central <ArrowRight/></a></section>
 <footer className="public-footer"><div className="public-brand"><span>EB</span><div><b>EB DO MIG</b><small>CENTRAL MILITAR</small></div></div><p>Sistema interno de organização, capacitação e comando.</p><nav><Link href="/termos">Termos de Uso</Link><Link href="/privacidade">Privacidade</Link><a href="#acesso">Acesso</a></nav><small>© {new Date().getFullYear()} EB DO MIG · Grupo 521106467</small></footer>
 </main>}
