'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Search,GraduationCap,ShieldAlert,CheckCircle2,Clock} from 'lucide-react';
import {RobloxIdentity} from './RobloxIdentity';
import {promotionTrainingType} from '@/lib/promotion-training-model';
import {PATENTES} from '@/lib/patentes';
type Mode='promotion'|'demotion';
type Change={groupId:number;community:string;userId:string;direction:Mode;current:{id:string;name:string;rank:number};target:{id:string;name:string;rank:number}};
type Member={userId:string;username:string;avatar?:string};
type Training={key:string;label:string};
const GROUPS=[{sigla:'EXÉRCITO',id:521106467},{sigla:'STAFF',id:319140811},{sigla:'BFE',id:34565583},{sigla:'CIE',id:729809284},{sigla:'BAC',id:886757353},{sigla:'BPE',id:710960394}];
export function RankChangeWorkflow({mode,preview=false,previewCanSkip=false,channel}:{mode:Mode;preview?:boolean;previewCanSkip?:boolean;channel?:string}){
  const isPromotion=mode==='promotion',accessChannel=channel||(isPromotion?'Entregar patente':'Rebaixamentos');
  const filtered=(groups:typeof GROUPS)=>accessChannel==='Promoção em divisão'?groups.filter(g=>g.id!==521106467):accessChannel==='Entregar patente'?groups.filter(g=>g.id===521106467):groups;
  const [groups,setGroups]=useState(()=>filtered(GROUPS)),[community,setCommunity]=useState(()=>filtered(GROUPS)[0]);
  const [search,setSearch]=useState(preview?'gabribor_sola':''),[member,setMember]=useState<Member|null>(null),[change,setChange]=useState<Change|null>(null);
  const [training,setTraining]=useState<Training|null>(null),[selection,setSelection]=useState<''|'training'|'none'>(''),[canSkip,setCanSkip]=useState(false),[reason,setReason]=useState('');
  const [step,setStep]=useState<'search'|'review'|'confirm'|'done'|'reconciliation'>('search'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[closesAt,setClosesAt]=useState('');
  const [demoRank,setDemoRank]=useState('808360028');
  useEffect(()=>{if(preview)return;const c=new AbortController();fetch('/api/divisions',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Não foi possível consultar as comunidades.');const d=await r.json();const available=filtered((d.divisions||[]).map((g:{sigla:string;groupId:number})=>({sigla:g.sigla,id:g.groupId})));setGroups(available);if(available.length)setCommunity(available[0]);else setError('Nenhuma comunidade disponível nesta guia.')}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[preview,accessChannel]); // eslint-disable-line react-hooks/exhaustive-deps
  function clear(){setChange(null);setMember(null);setTraining(null);setSelection('');setReason('');setError('');setStep('search');setClosesAt('')}
  async function lookup(event:React.FormEvent){event.preventDefault();if(!search.trim()||busy)return;clear();setBusy(true);
    try{
      if(preview){const rank=PATENTES.find(r=>r.roleId===demoRank)!,next=PATENTES.find(r=>r.ordem===rank.ordem+(isPromotion?1:-1));if(!next)throw Error('Sem cargo de destino disponível.');const current={id:rank.roleId,name:'['+rank.sigla+'] '+rank.nome,rank:rank.ordem};setMember({userId:'demo-militar',username:search.trim()});setChange({groupId:community.id,community:community.sigla,userId:'demo-militar',direction:mode,current,target:{id:next.roleId,name:'['+next.sigla+'] '+next.nome,rank:next.ordem}});setTraining(promotionTrainingType(community.id,community.sigla,current));setCanSkip(previewCanSkip);setStep('review');return}
      const response=await fetch('/api/ranks/change',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:search.trim(),groupId:community.id,direction:mode,channel:accessChannel,confirm:false})});const data=await response.json();if(!response.ok)throw Error(data.error);setMember(data.member);setChange(data.change);setTraining(data.training);setCanSkip(data.canSkipTraining===true);setStep('review');
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar o militar.')}finally{setBusy(false)}
  }
  const minReason=selection==='none'?10:5,ready=!!change&&(!isPromotion||!!selection)&&reason.trim().length>=minReason;
  async function apply(){if(!ready||busy||step!=='confirm')return;setBusy(true);setError('');
    try{if(preview){setClosesAt(selection==='training'?new Date(Date.now()+900000).toISOString():'');setStep('done');return}
      const r=await fetch('/api/ranks/change',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:member!.userId,groupId:community.id,direction:mode,channel:accessChannel,confirm:true,targetRoleId:change!.target.id,reason:reason.trim(),trainingMode:isPromotion?selection:undefined,trainingKey:selection==='training'?training?.key:undefined})});const d=await r.json();if(!r.ok){if(d.reconciliation){setStep('reconciliation');setError(d.error);return}throw Error(d.error)}setChange(d.change);setClosesAt(d.trainingWindow?.closesAt||'');setStep('done');
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar a alteração.');setStep('review')}finally{setBusy(false)}
  }
  return <div className="promotion-workspace"><section className="promotion-intro"><span className="promotion-emblem"><GraduationCap size={30}/></span><div><h2>{isPromotion?'Quem você vai promover hoje?':'Consultar rebaixamento'}</h2><p>{isPromotion?'Localize o militar, confira a patente e registre como a promoção foi conquistada.':'Confira o militar e justifique a alteração de patente.'}</p></div>{preview&&<span className="m-tag">Demonstração</span>}</section>
    <section className="m-panel promotion-search-panel"><form onSubmit={lookup}><label>Comunidade<select disabled={busy||step==='confirm'} value={community.id} onChange={e=>{setCommunity(groups.find(g=>g.id===Number(e.target.value))!);clear()}}>{groups.map(g=><option value={g.id} key={g.id}>{g.sigla}</option>)}</select></label><label className="promotion-search-label">Username do Roblox<div><Search size={19} aria-hidden="true"/><input required maxLength={20} placeholder="Ex.: gabribor_sola" value={search} disabled={busy||step==='confirm'} onChange={e=>{setSearch(e.target.value);clear()}}/></div></label><button className="m-button primary" disabled={busy||!groups.length||step==='confirm'}>{busy?'Consultando…':'Buscar militar'}</button></form>{preview&&<label className="preview-rank-picker">Patente para simulação<select value={demoRank} disabled={busy} onChange={e=>{setDemoRank(e.target.value);clear()}}>{PATENTES.filter(r=>r.ordem>=(isPromotion?1:2)&&r.ordem<=23).map(r=><option value={r.roleId} key={r.roleId}>{r.nome}</option>)}</select></label>}</section>
    {error&&<div className="m-alert" role="alert">{error}</div>}
    {member&&change&&<section className="m-panel promotion-target"><div className="promotion-target-head"><RobloxIdentity userId={preview?undefined:member.userId} username={member.username} avatar={member.avatar} detail={community.sigla}/><span className="m-tag">{step==='done'?'Alteração confirmada':'Militar localizado'}</span></div>
      <div className="promotion-path"><div><small>{step==='done'?'Patente anterior':'Patente atual'}</small><b>{change.current.name}</b></div><ArrowRight size={24} aria-hidden="true"/><div><small>{step==='done'?'Novo cargo':isPromotion?'Próxima patente':'Cargo de destino'}</small><b>{change.target.name}</b></div></div>
      {step==='done'?<div className="promotion-success" role="status"><CheckCircle2 size={30}/><h3>{preview?'Simulação concluída':isPromotion?'Promoção confirmada':'Rebaixamento confirmado'}</h3><p>{preview?'Nenhum cargo real foi alterado.':member.username+' agora está como '+change.target.name+'.'}</p>{isPromotion&&<p>{selection==='none'?'Promoção sem treino: o motivo foi registrado e não soma treino ao ranking.':closesAt?'Esta promoção integra '+training?.label+'. A janela termina às '+new Date(closesAt).toLocaleTimeString('pt-BR')+'.':'Registro atualizado.'}</p>}<button className="m-button" onClick={clear}>Consultar outro militar</button></div>:step==='reconciliation'?<div className="promotion-reconciliation"><ShieldAlert size={28}/><h3>Confira o cargo e os registros</h3><p>O novo envio está bloqueado nesta ficha. Verifique o Roblox, os logs e a CDP com um Criador antes de prosseguir.</p></div>:<>
        {isPromotion&&<fieldset className="promotion-options" disabled={busy||step==='confirm'}><legend>Como foi essa promoção?</legend><p>O treino disponível corresponde à patente atual. Promoções do mesmo tipo formam uma sessão de até 15 minutos; trocar de formação encerra a anterior.</p><div><button type="button" aria-pressed={selection==='training'} className={selection==='training'?'chosen':''} onClick={()=>setSelection('training')}><GraduationCap size={23}/><span><b>{training?.label}</b><small>Registrar no treino deste instrutor</small></span></button>{canSkip&&<button type="button" aria-pressed={selection==='none'} className={'without-training '+(selection==='none'?'chosen':'')} onClick={()=>setSelection('none')}><ShieldAlert size={23}/><span><b>Sem treino</b><small>Moderador ou superior · exige motivo</small></span></button>}</div></fieldset>}
        {(!isPromotion||selection)&&<label className="promotion-reason">{selection==='none'?'Por que esta promoção será feita sem treino?':'Motivo da alteração'}<textarea rows={3} minLength={minReason} maxLength={500} disabled={busy||step==='confirm'} value={reason} onChange={e=>setReason(e.target.value)} placeholder={selection==='none'?'Explique a autorização ou a correção que justifica a promoção.':'Informe a formação concluída ou a justificativa da alteração.'}/><small>{reason.trim().length}/500 caracteres · mínimo {minReason}</small></label>}
        {step==='confirm'?<div className="promotion-confirm"><h3>{isPromotion?'Confirmar promoção':'Confirmar rebaixamento'}{selection==='none'?' sem treino':''}</h3><p><b>{member.username}</b> passará de {change.current.name} para <b>{change.target.name}</b>.</p><p>{selection==='none'?'Esta ação não registra treinamento no ranking.':'Formação: '+(training?.label||'Não se aplica')+'.'}</p><blockquote>{reason}</blockquote><div><button className="m-button" disabled={busy} onClick={()=>setStep('review')}>Voltar</button><button className="m-button primary" disabled={busy} onClick={apply}>{busy?'Enviando…':preview?'Confirmar simulação':'Confirmar alteração no Roblox'}</button></div></div>:<button className="m-button primary promotion-submit" disabled={!ready||busy} onClick={()=>setStep('confirm')}><ArrowUpRight size={19}/>{isPromotion?(selection?selection==='none'?'Revisar promoção sem treino':'Promover via '+training?.label:'Escolha como foi a promoção'):'Revisar rebaixamento'}</button>}
      </>}
    </section>}
    <aside className="promotion-note"><Clock size={20}/><p>O prazo começa no primeiro UP e não reinicia a cada militar. A troca de formação abre um novo treino. Promoções sem treino continuam respeitando a CDP.</p></aside>
  </div>;
}
