const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),test=require('node:test'),assert=require('node:assert/strict');
function load(file,mocks={}){const filename=path.join(__dirname,'..',file),exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n in mocks)return mocks[n];throw Error('Missing '+n)},Date,Map,Set,crypto,console:{error:()=>{}},Response,Request},{filename});return exports}
const policy=load('lib/promotion-policy.ts',{'./roblox':{}});
test('Sem treino uses the actual main-group MOD rank; booleans or unrelated roles cannot grant it',()=>{const roles=[{id:'soldado',rank:2},{id:'general',rank:16},{id:'808432019',rank:27},{id:'admin',rank:29},{id:'creator',rank:255}];for(const id of ['soldado','general','unknown'])assert.equal(policy.isModeratorOrAbove(id,roles),false);for(const id of ['808432019','admin','creator'])assert.equal(policy.isModeratorOrAbove(id,roles),true);assert.equal(policy.isModeratorOrAbove('creator',roles.filter(r=>r.id!=='808432019')),false)});
function harness({canSkip=false,fail=false,recordFails=false}={}){let applied=0,recorded=[];const change={groupId:521106467,community:'EXÉRCITO',userId:'123',current:{id:'808360028',name:'Recruta',rank:1},target:{id:'807380036',name:'Soldado',rank:2}};const api=load('app/api/ranks/change/route.ts',{
  'next/server':{NextResponse:{json:(data,init)=>Response.json(data,init)}},'@/lib/auth':{getSessionUser:async()=>({id:'1',username:'Instrutor',isAdmin:true})},'@/lib/authorize':{sameOrigin:()=>true,authorizedFor:async()=>true,currentCreator:async()=>false},'@/lib/roblox':{previewRankChange:async()=>change,applyRankChange:async()=>{if(fail)throw Error('Roblox recusou');applied++;return change}},'@/lib/roblox-identities':{resolveRobloxIdentity:async()=>({id:'123',username:'Militar',avatar:'https://tr.rbxcdn.com/head.png'})},'@/lib/promotion-policy':{canSkipPromotionTraining:async()=>canSkip},'@/lib/promotion-training-model':{promotionTrainingType:()=>({key:'normal',label:'Normal'})},'@/lib/promotion-training':{ensurePromotionTrainingSchema:async()=>{},recordRankActivity:async data=>{if(recordFails)throw Error('DB offline');recorded.push(data);return null}},'@/lib/cdp':{assertPromotionCdpAvailable:async()=>{},startPromotionCdp:async()=>null},'@/lib/activity-db':{recordActivity:async()=>{}},'@/lib/db':{isDatabaseConfigured:()=>true},'@/lib/discord-logs':{sendSiteLog:async()=>true}});
  return {call:body=>api.POST(new Request('https://mig.test/api/ranks/change',{method:'POST',body:JSON.stringify({userId:'123',groupId:521106467,direction:'promotion',confirm:true,targetRoleId:change.target.id,trainingMode:'training',trainingKey:'normal',reason:'Treinamento concluído.',...body})})),stats:()=>({applied,recorded})};
}
test('forged Sem treino by a lower rank is rejected before Roblox or audit mutation',async()=>{const h=harness();const r=await h.call({trainingMode:'none'});assert.equal(r.status,403);assert.equal(h.stats().applied,0);assert.equal(h.stats().recorded.length,0)});
test('MOD+ without-training promotion requires explanation and records it without counting a training',async()=>{const h=harness({canSkip:true});assert.equal((await h.call({trainingMode:'none',reason:'curto'})).status,422);assert.equal(h.stats().applied,0);assert.equal((await h.call({trainingMode:'none',reason:'Correção de patente autorizada.'})).status,200);assert.equal(h.stats().recorded[0].countsAsTraining,false);assert.match(h.stats().recorded[0].description,/Sem treino.*Correção de patente autorizada/)});
test('unselected or incompatible training is refused and the valid type counts after a confirmed UP',async()=>{const h=harness();assert.equal((await h.call({trainingKey:'esa'})).status,422);assert.equal((await h.call({trainingMode:undefined})).status,422);assert.equal(h.stats().applied,0);assert.equal((await h.call({})).status,200);assert.equal(h.stats().recorded[0].countsAsTraining,true)});
test('read-only promotion preview returns identity and server-authorized choices without changing ranks',async()=>{const h=harness();const r=await h.call({confirm:false});const d=await r.json();assert.equal(d.member.username,'Militar');assert.equal(d.canSkipTraining,false);assert.equal(d.training.key,'normal');assert.equal(h.stats().applied,0)});
test('Roblox failure does not count; post-write persistence failure explicitly requires reconciliation',async()=>{const fail=harness({fail:true});assert.equal((await fail.call({})).status,502);assert.equal(fail.stats().recorded.length,0);const db=harness({recordFails:true});const d=await(await db.call({})).json();assert.equal(d.applied,true);assert.equal(d.reconciliation,true);assert.match(d.error,/Não repita/)});
