import {NextResponse} from 'next/server';
import {getSessionUser} from '@/lib/auth';
import {sameOrigin,currentCreator} from '@/lib/authorize';
import {rewardOverview,previewReward,redeemReward,createReward,manageReward} from '@/lib/rewards';
import {getLiveHierarchies} from '@/lib/roblox';
export const dynamic='force-dynamic';
type Session={exp:number;id:string;username:string};
const reply=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'cache-control':'no-store'}});
export async function GET(request:Request){const actor=await getSessionUser<Session>(request);if(!actor)return reply({error:'Entre novamente para consultar os resgates.'},401);try{const creator=new URL(request.url).searchParams.get('creator')==='1';if(creator&&!await currentCreator(request))return reply({error:'Acesso exclusivo de Criadores.'},403);return reply({...await rewardOverview(actor,creator),groups:creator?await getLiveHierarchies():undefined})}catch{return reply({error:'Não foi possível consultar as recompensas. Verifique a conexão do banco e do Roblox.'},503)}}
export async function POST(request:Request){const actor=await getSessionUser<Session>(request);if(!actor)return reply({error:'Entre novamente para resgatar.'},401);if(!sameOrigin(request))return reply({error:'Origem não permitida.'},403);try{const body=await request.json();if(!body||typeof body!=='object'||Array.isArray(body))return reply({error:'Solicitação inválida.'},400);if(['create','disable','deliver'].includes(body.action)){if(!await currentCreator(request))return reply({error:'Acesso exclusivo de Criadores.'},403);if(body.action==='create')return reply(await createReward(body,actor),201);await manageReward(body,actor);return reply({message:'Registro atualizado.'})}if(body.action==='preview')return reply({reward:await previewReward(body.code,actor)});if(body.action==='redeem')return reply(await redeemReward(body.code,actor));return reply({error:'Ação inválida.'},400)}catch(error){const message=error instanceof Error?error.message:'';const safe=/código|Código|caracteres|patente|Patente|recompensa|Escolha|Selecione|validade|Defina|resgat|comunidade|CDP|Muitas|Aguarde|entrega|Roblox ainda/i.test(message);return reply({error:safe?message:'Não foi possível concluir. Atualize o histórico antes de tentar novamente.'},/Muitas/.test(message)?429:409)}}
