export interface Activity {id:string;tipo:string;userId:string;username:string;descricao:string;timestamp:string;autorId?:string;autorUsername?:string;autorAvatar?:string}
export interface RosterMember {userId:string;username:string;rankName:string;division:string;avatar?:string;roleId:string;rankNumber:number;divisions?:string[];cdpFim?:string|null}
export interface ManagerData {totalSincronizados:number;emCdp:number;treinosMes:number;acoesRegistradas:number;ultimaSincronizacao:string|null;divisoes:Record<string,number>;atividadesRecentes:Activity[];cdpMembers?:RosterMember[];auditAvailable?:boolean}
export const EVENT_LABELS:Record<string,string>={promocao:'Promoção',rebaixamento:'Rebaixamento',treino:'Treinamento',cdp_inicio:'CDP iniciada',cdp_conclusao:'CDP concluída',cdp_cancelamento:'CDP cancelada',anuncio:'Anúncio',verificacao:'Sincronização',login:'Acesso'};
export function filterActivities(logs:Activity[],query:string,type:string){const q=query.trim().toLocaleLowerCase('pt-BR');return logs.filter(l=>(!type||l.tipo===type)&&`${l.username} ${l.userId} ${l.autorUsername||''} ${l.descricao}`.toLocaleLowerCase('pt-BR').includes(q))}
export function trainingRanking(logs:Activity[]){const entries=new Map<string,{id:string;name:string;avatar?:string;count:number}>();for(const l of logs){if(l.tipo!=='treino'||!l.autorId)continue;const item=entries.get(l.autorId)||{id:l.autorId,name:l.autorUsername||l.autorId,avatar:l.autorAvatar,count:0};item.count++;if(!item.avatar&&l.autorAvatar)item.avatar=l.autorAvatar;entries.set(l.autorId,item)}return [...entries.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name))}
export function remainingCdp(end:string,now:number){const remaining=new Date(end).getTime()-now;if(!Number.isFinite(remaining))return 'Prazo indisponível';if(remaining<=0)return 'Período concluído';const minutes=Math.ceil(remaining/60000);return minutes>=1440?`${Math.floor(minutes/1440)}d ${Math.floor(minutes%1440/60)}h`:minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}min`:`${minutes}min`}
export const CREATOR_ROLE_ID='808700015';
export function isCreatorRole(roleId?:string){return roleId===CREATOR_ROLE_ID}
