import type{Metadata}from'next';
import{ContactBlock,LegalPage}from'../components/LegalPage';

export const metadata:Metadata={title:'Política de Privacidade | EB DO MIG',description:'Como a Central Militar EB DO MIG utiliza e protege dados do Roblox.'};

export default function Privacidade(){
  return <LegalPage eyebrow="DOCUMENTO PÚBLICO" title="Política de Privacidade" summary="Esta política explica quais dados a Central Militar usa, por que eles são necessários e como o usuário pode exercer seus direitos.">
    <section><h2>1. Responsável e abrangência</h2><p>A Central Militar EB DO MIG é uma ferramenta de gestão do grupo Roblox 521106467 e de suas divisões. Esta política se aplica ao site, ao login com Roblox e às funções internas do painel.</p></section>
    <section><h2>2. Dados utilizados</h2><p>Ao autorizar o login, recebemos somente os dados permitidos pelos escopos <code>openid</code> e <code>profile</code>:</p><ul><li>ID, nome de usuário e nome de exibição no Roblox;</li><li>imagem pública do avatar;</li><li>participação, cargo e patente nos grupos do EB DO MIG e de suas divisões;</li><li>registros administrativos gerados no uso do painel, como treinamentos e ações de moderação, quando essas funções estiverem habilitadas.</li></ul><p>Nunca solicitamos nem armazenamos a senha da conta Roblox.</p></section>
    <section><h2>3. Finalidades</h2><p>Esses dados são usados para autenticar o usuário, confirmar sua participação e hierarquia, aplicar permissões, apresentar o efetivo real das divisões, manter registros de segurança e operar as funções administrativas solicitadas pelo próprio grupo.</p></section>
    <section><h2>4. Cookies e sessão</h2><p>Usamos um cookie temporário de segurança durante o OAuth, com duração máxima de 10 minutos, e um cookie de sessão protegido, com duração máxima de 24 horas. Eles são necessários para impedir falsificação de login e manter o acesso autenticado. O logout remove a sessão do navegador.</p></section>
    <section><h2>5. Compartilhamento e fornecedores</h2><p>Os dados podem ser processados pela Roblox para autenticação e consulta dos grupos, pela Vercel para hospedar e entregar o site e, se a administração configurar essa função, pelo Discord para registros internos de ações. Compartilhamos apenas o necessário para cada finalidade.</p><p>Não vendemos dados, não usamos dados para publicidade comportamental, não rastreamos usuários fora do serviço e não utilizamos os dados para treinar modelos de inteligência artificial.</p></section>
    <section><h2>6. Retenção e segurança</h2><p>A sessão expira automaticamente em até 24 horas. Registros administrativos, quando habilitados, são mantidos somente pelo período necessário à segurança e à gestão do grupo. Usamos conexão HTTPS, cookies HTTP-only, validação de estado, PKCE e assinatura da sessão. Nenhum sistema é completamente imune a falhas, mas adotamos medidas proporcionais ao serviço.</p></section>
    <section><h2>7. Direitos do usuário</h2><p>O usuário pode solicitar acesso, correção ou exclusão de registros administrativos associados à sua conta. O logout remove apenas a sessão local; para excluir registros persistentes, é necessário enviar uma solicitação à administração. Dados públicos mantidos pela própria Roblox devem ser alterados diretamente na conta Roblox.</p></section>
    <section><h2>8. Idade e uso permitido</h2><p>O serviço é destinado a usuários autorizados a utilizar a Roblox e a participar do grupo, observadas as regras de idade, supervisão e consentimento aplicáveis à conta.</p></section>
    <section><h2>9. Alterações desta política</h2><p>Esta política poderá ser atualizada para refletir mudanças técnicas, legais ou operacionais. A data da versão atual ficará sempre visível nesta página.</p></section>
    <section><h2>10. Contato</h2><ContactBlock/></section>
  </LegalPage>;
}
